name: iv_project_web_app
description: "In Vite Project Web App"
publish_to: "none"
version: 0.1.5

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  iv_project_model:
    path: ../iv_project_model

  iv_project_web_data:
    path: ../iv_project_web_data

  iv_project_core:
    path: ../iv_project_core

  iv_project_widget_core:
    path: ../iv_project_widget_core

  iv_project_invitation_theme:
    path: ../iv_project_invitation_theme

  quick_dev_sdk:
    path: ../quick_dev_sdk

  go_router: ^17.0.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
