name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"

      - name: Enable Web & skwasm
          run: |
            flutter config --enable-web
            flutter build web --wasm --release

      - name: Upload artifact (optional)
          uses: actions/upload-artifact@v3
          with:
            name: web-build
            path: build/web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.IV_PROJECT_WEB_APP }}
          vercel-org-id: ${{ secrets.IV_PROJECT_WEB_APP_ORG_ID }}
          vercel-project-id: ${{ secrets.IV_PROJECT_WEB_APP_PROJECT_ID }}
          working-directory: ./build/web
          scope: personal